package com.finance.bank.presentation.controllers;

import com.finance.bank.exception.InvalidAccountException;
import com.finance.bank.model.*;
import com.finance.bank.presentation.util.AlertHelper;
import com.finance.bank.presentation.util.SessionManager;
import com.finance.bank.service.BankService;
import com.finance.bank.util.IdGenerator;
import com.finance.bank.util.NumberFormatter;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;

import java.math.BigDecimal;
import java.net.URL;
import java.util.ResourceBundle;

/**
 * Controller for the Open Account screen.
 * 3-step flow: (1) Find Customer by National ID,
 *              (2) Select Account Type (Savings / Current),
 *              (3) Submit via BankService.openAccount().
 *
 * Account numbers are generated by IdGenerator.generateAccountNumber()
 * which guarantees the correct 16-digit bank prefix (10010001XXXXXXXX).
 */
public class AccountFormController implements Initializable, EmployeeAware {

    @FXML private TextField     nationalIdField;
    @FXML private HBox          customerFoundBox;
    @FXML private Label         foundCustomerName;
    @FXML private Label         foundCustomerNid;
    @FXML private ToggleButton  savingsToggle;
    @FXML private ToggleButton  currentToggle;
    @FXML private VBox          savingsInfo;
    @FXML private VBox          overdraftBox;
    @FXML private TextField     overdraftField;
    @FXML private Label         generatedAccountLabel;
    @FXML private Button        openAccountButton;
    @FXML private VBox          resultCard;
    @FXML private Label         resultAccountNumber;
    @FXML private Label         resultAccountType;
    @FXML private Label         resultOwner;
    @FXML private VBox          alertContainer;

    private final BankService bankService = BankService.getInstance();
    private Customer selectedCustomer;
    private String   generatedAccountNumber;

    @Override
    public void setEmployee(Employee employee) {
        // Employee is available via SessionManager when needed.
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        // Create a toggle group so only one can be selected at a time
        ToggleGroup group = new ToggleGroup();
        savingsToggle.setToggleGroup(group);
        currentToggle.setToggleGroup(group);

        // Generate the first account number on load
        generatedAccountNumber = IdGenerator.generateAccountNumber();
        generatedAccountLabel.setText(NumberFormatter.mask(generatedAccountNumber, 4));

        // Savings toggle listener
        savingsToggle.selectedProperty().addListener((obs, old, selected) -> {
            if (selected) {
                savingsInfo.setVisible(true);
                savingsInfo.setManaged(true);
                overdraftBox.setVisible(false);
                overdraftBox.setManaged(false);
                stylizeToggle(savingsToggle, true);
                stylizeToggle(currentToggle, false);
            }
        });

        // Current toggle listener
        currentToggle.selectedProperty().addListener((obs, old, selected) -> {
            if (selected) {
                overdraftBox.setVisible(true);
                overdraftBox.setManaged(true);
                savingsInfo.setVisible(false);
                savingsInfo.setManaged(false);
                stylizeToggle(currentToggle, true);
                stylizeToggle(savingsToggle, false);
            }
        });
    }

    @FXML
    private void handleSearchCustomer() {
        clearAlerts();
        String nationalId = nationalIdField.getText().trim();
        if (nationalId.isEmpty()) {
            showError("Please enter a National ID.");
            return;
        }

        Customer customer = bankService.findCustomerByNationalId(nationalId);
        if (customer == null) {
            showError("No customer found with National ID: " + nationalId);
            customerFoundBox.setVisible(false);
            customerFoundBox.setManaged(false);
            selectedCustomer = null;
            return;
        }

        selectedCustomer = customer;
        foundCustomerName.setText(customer.getName());
        foundCustomerNid.setText("National ID: " + customer.getNationalId()
                + "  \u2502  Accounts: " + customer.getAccounts().size());
        customerFoundBox.setVisible(true);
        customerFoundBox.setManaged(true);
    }

    @FXML
    private void handleOpenAccount() {
        clearAlerts();

        Employee employee = SessionManager.getEmployee();
        if (employee == null) {
            showError("Session expired. Please log in again.");
            return;
        }
        if (selectedCustomer == null) {
            showError("Please search and select a customer first.");
            return;
        }

        Toggle selected = savingsToggle.getToggleGroup().getSelectedToggle();
        if (selected == null) {
            showError("Please select an account type (Savings or Current).");
            return;
        }

        try {
            Account account;
            if (selected == savingsToggle) {
                account = new SavingsAccount(generatedAccountNumber, selectedCustomer);
            } else {
                String overdraftText = overdraftField.getText().trim();
                if (overdraftText.isEmpty()) {
                    showError("Please enter an overdraft limit for Current Account.");
                    overdraftField.requestFocus();
                    return;
                }
                BigDecimal overdraft = new BigDecimal(overdraftText);
                if (overdraft.compareTo(BigDecimal.ZERO) < 0) {
                    showError("Overdraft limit must be zero or positive.");
                    return;
                }
                account = new CurrentAccount(generatedAccountNumber, selectedCustomer, overdraft);
            }

            bankService.openAccount(employee, account);
            showSuccess("Account opened successfully for " + selectedCustomer.getName() + "!");
            displayResult(account, selectedCustomer);

            // Prepare a fresh account number for the next account
            generatedAccountNumber = IdGenerator.generateAccountNumber();
            generatedAccountLabel.setText(NumberFormatter.mask(generatedAccountNumber, 4));

        } catch (NumberFormatException e) {
            showError("Invalid overdraft amount. Please enter a valid number (e.g. 5000.00).");
        } catch (InvalidAccountException e) {
            showError("Account validation error: " + e.getMessage());
        } catch (Exception e) {
            showError(e.getMessage());
        }
    }

    @FXML
    private void handleReset() {
        nationalIdField.clear();
        overdraftField.clear();
        customerFoundBox.setVisible(false);
        customerFoundBox.setManaged(false);
        savingsInfo.setVisible(false);
        savingsInfo.setManaged(false);
        overdraftBox.setVisible(false);
        overdraftBox.setManaged(false);
        savingsToggle.setSelected(false);
        currentToggle.setSelected(false);
        selectedCustomer = null;
        resultCard.setVisible(false);
        resultCard.setManaged(false);
        clearAlerts();
        generatedAccountNumber = IdGenerator.generateAccountNumber();
        generatedAccountLabel.setText(NumberFormatter.mask(generatedAccountNumber, 4));
    }

    private void displayResult(Account account, Customer owner) {
        resultAccountNumber.setText(account.getAccountNumber());
        resultAccountType.setText(account.getAccountType().label());
        resultOwner.setText(owner.getName());
        resultCard.setVisible(true);
        resultCard.setManaged(true);
    }

    private void stylizeToggle(ToggleButton btn, boolean active) {
        if (active) {
            btn.setStyle("-fx-pref-width: 180; -fx-pref-height: 50; "
                    + "-fx-background-radius: 8; -fx-border-radius: 8; "
                    + "-fx-border-width: 2; -fx-cursor: hand; -fx-font-size: 13px; "
                    + "-fx-background-color: #1E4D8C; -fx-text-fill: white; "
                    + "-fx-border-color: #1E4D8C;");
        } else {
            btn.setStyle("-fx-pref-width: 180; -fx-pref-height: 50; "
                    + "-fx-background-radius: 8; -fx-border-radius: 8; "
                    + "-fx-border-width: 1.5; -fx-cursor: hand; -fx-font-size: 13px; "
                    + "-fx-background-color: white; -fx-text-fill: #1A2B4A; "
                    + "-fx-border-color: #DDE3EE;");
        }
    }

    private void showError(String message) {
        AlertHelper.showAlert(alertContainer, message, AlertHelper.AlertType.ERROR);
    }

    private void showSuccess(String message) {
        AlertHelper.showAlert(alertContainer, message, AlertHelper.AlertType.SUCCESS);
    }

    private void clearAlerts() {
        alertContainer.getChildren().clear();
    }
}
